package com.dynamocrud.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Time;
import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "cita")
public class Cita {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idCita;
    @DynamoDBAttribute
    private String descripcion;
    @DynamoDBAttribute
    private LocalDate fecha;
    @DynamoDBAttribute
    private Time hora;
    @DynamoDBAttribute
    private int numeroDosis;

    @DynamoDBAttribute
    private Usuario idUsuario;
    @DynamoDBAttribute
    private TipoVacuna TipoVacuna;
    @DynamoDBAttribute
    private LugarVacunacion LugarVacunacion;
}
