package com.dynamocrud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "lugarVacunacion")
public class LugarVacunacion {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idLugarVacunacion;
    @DynamoDBAttribute
    private String nombreCentroVacunacion;
    @DynamoDBAttribute
    private String direccion;
    @DynamoDBAttribute
    private String provincia;
    @DynamoDBAttribute
    private String canton;
    @DynamoDBAttribute
    private String distrito;


}