package com.dynamocrud.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "tipoVacuna")
public class TipoVacuna {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idTipoVacuna;
    @DynamoDBAttribute
    private int cantidadDosis;
    @DynamoDBAttribute
    private String nombreVacuna;

}
